"""
Django settings for quizz_project project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
# sdfds
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!+_nt77_ceyty6ya9rgstlg0!8u1%oxla=zy43p6#lqh@igi#x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'quizz_app',
    'rest_framework',
    'corsheaders',
    'knox',
    'phonenumber_field',
    'moncashify',
    'import_export'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ORIGIN_WHITELIST = [
#     "http://localhost:3000",
#     "http://localhost:8000",
# ]

CORS_ORIGIN_ALLOW_ALL = True # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'quizz_app.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ROOT_URLCONF = 'quizz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quizz_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, 'db.sqlite3')
    }
}


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'America/Port-au-Prince'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'frontend', "build", "static"),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
#site id
# SITE_ID = 1
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
# PHONENUMBER_DEFAULT_REGION = 'HT'
#gmail config
########## EMAIL CONFIGURATION
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'htbonmache@gmail.com'
EMAIL_HOST_PASSWORD = 'jepasse509haiti'
EMAIL_SUBJECT_PREFIX = '[QuizaPay]'
ADMINS = (
    ("Castin Stanley", "stanleycastin19@gmail.com"),
    ("Compte Admin", "quizapay@gmail.com"),
    # ("Wenderson Beauchamps", "wendersonbeauchamps@yahoo.fr"),
    # ("Compte Admin", "htbonmache@gmail.com"),
)
#moncash keys
MONCASH_CLIENT_ID = 'f6e62a0bd9faa11b5a528730eff5a433'
MONCASH_SECRET_KEY = 'BUtONTNoLDzWmW8925aSEOm95JR6FV62mjpQLaODFs4Y-RBEIcKR9F3FSP5QEcI3'

CHOICES_CITY = (
    
    ("Département de l’Ouest", (
        ("6110","Port-au-Prince"),
        ("6111","Bel-Air et Bourdon"),
        ("6112","Bas Peu de Choses"),
        ("6113","Turgeau"),
        ("6114","Bois Verna"),
        ("6116","Carrefour Feuilles"),
        ("6117","Morne de l’Hôpital"),
        ("6118","Bolosse"),
        ("6119","Martissant et Fontamara"),
        ("6120","Delmas"),
        ("6121","Varreux"),
        ("6122","Cité soleil"),
        ("6123","Maïs Gâté, Tabarre zone 1"),
        ("6124","Petite Place Cazeau, Tabarre zone 2"),
        ("6125","Croix-des-Missions"),
        ("6130","Carrefour"),
        ("6131","Bizoton"),
        ("6132","Diquini, Thor"),
        ("6133","Côte-Page, Mahotière"),
        ("6134","Arcachon, Warney"),
        ("6135","Brochette"),
        ("6136","Lamentin, Mariani, Merger"),
        ("6140","Pétion-Ville"),
        ("6141","Frères, pergnier"),
        ("6142","Pèlerin"),
        ("6143","Tête de l’Eau"),
        ("6144","Laboule"),
        ("6145","Thomassin"),
        ("6146","Fermathe"),
        ("6147","Pergnier"),
        ("6150","Kenscoff"),
        ("6160","Gressier"),
        ("6210","Léogâne"),
        ("6211","Trouin"),
        ("6212","Orangers"),
        ("6220","PetitGoâve"),
        ("6221","Vialet"),
        ("6230","Grand Goâve"),
        ("6310","Croix-des-Bouquets"),
        ("6311","Santo"),
        ("6312","Bon Repos"),
        ("6320","Thomazeau"),
        ("6330","Ganthier"),
        ("6331","Fonds Parisien et Galette Bonbon"),
        ("6330","Cornillon"),
        ("6340","Fonds Verettes"),
        ("6410","Arcahaie"),
        ("6411","Saintard"),
        ("6420","Cabaret"),
        ("6421","Casale"),
        ("6510","Anse à Galets (La Gonâve)"),
        ("6520","Pointe à Raquette (La Gonâve)"),
    )),

    ("Département de l’Artibonite", (
        ("4110","Gonaives"),
        ("4111","Petite Rivière de l’Artibonite"),
        ("4120","Ennery"),
        ("4130","L’Estère"),
        ("4210","Gros Morne"),
        ("4220","Terre Neuve"),
        ("4230","Anse Rouge"),
        ("4231","Sources Chaudes"),
        ("4310","Saint Marc"),
        ("4311","Montrouis"),
        ("4320","Verrettes"),
        ("4321","Désarmes"),
        ("4322","Deschapelles"),
        ("4323","Liancourt"),
        ("4410","Dessalines / Marchand"),
        ("4420","Petite Rivière del’Artibonite"),
        ("4421","Savane à Roches"),
        ("4430","Grande Saline"),
        ("4440","Desdunes"),
        ("4510","Marmelade"),
        ("4520","Saint Michel de l’Attalaye"),
    )),

    ("Département de la Grande Anse", (
        ("7110","Jérémie"),
        ("7111","Léon"),
        ("7112","Marfranc"),
        ("7120","Abricot"),
        ("7130","Bonbon"),
        ("7140","Moron"),
        ("7141","Sources Chaudes"),
        ("7150","Chambellan"),
        ("7210","Anse d’Hainault"),
        ("7220","Dame-Marie"),
        ("7221","lesson"),
        ("7230","LesIrois"),
        ("7231","Carcasse"),
        ("7310","Corail"),
        ("7320","Roseaux"),
        ("7330","Beaumont"),
        ("7340","Pestel"),
    )),

    ("Département de Nippes", (
        ("7410","Miragoâne"),
        ("7411","Saint Michel du Sud"),
        ("7412","Paillant"),
        ("7413","Fond des Nègres"),
        ("7420","Petite Rivière de Nippes"),
        ("7510","Anse-à-Veau"),
        ("7520","Baradères"),
        ("7521","Grand Boucan"),
        ("7530","Petit Trou de Nippes"),
        ("7540","L’Asile"),
    )),

    ("Département du Centre", (
        ("5110","Hinche"),
        ("5111","Los Palis"),
        ("5120","Maïssade"),
        ("5121","Louverture"),
        ("5130","Thomonde"),
        ("5140","Cerca Cavajal"),
        ("5210","Mirebalais"),
        ("5211","Dufailly"),
        ("5220","Saut d’Eau"),
        ("5230","Boucan Carré"),
        ("5231","Péligre"),
        ("5310","Lascahobas"),
        ("5320","Belladères"),
        ("5330","Savanette"),
        ("5321","Baptiste"),
        ("5410","Cerca-la-Source"),
        ("5411","Saltadère"),
        ("5412","La Mielle"),
        ("5420","Thomassique"),
    )),

    ("Département du Nord", (
        ("1110","Cap-Haïtien (la ville)"),
        ("1111","Bande du Nord (quartier du Cap)"),
        ("1112","Labadie (quartier du Cap)"),
        ("1113","Haut du Cap (quartier du Cap)"),
        ("1114","Petite Anse"),
        ("1120","Quartier Morin"),
        ("1130","Limonade"),
        ("1210","Acul du Nord"),
        ("1211","La Soufrière"),
        ("1220","Plaine du Nord"),
        ("1221","Robillard"),
        ("1230","Milot"),
        ("1231","Carrefour des Pères"),
        ("1310","Grande Rivière du Nord et"),
        ("1320","Barbon"),
        ("1410","Saint Raphaël"),
        ("1420","Dondon"),
        ("1430","Ranquitte"),
        ("1440","Pignon"),
        ("1450","La Victoire"),
        ("1510","Borgne"),
        ("1511","Petit bourg de Borgne"),
        ("1517","Côte de Fer et Fond"),
        ("1520","Port-Margot"),
        ("1521","Bayeux"),
        ("1522","Margot"),
        ("1610","Limbé"),
        ("1611","Camp Coq"),
        ("1620","Bas Limbé"),
        ("1710","Plaisance"),
        ("1720","Pilate"),
        ("1723","Ravine Trompette"),
    )),

    ("Département du Nord-Est", (
        ("2110","Fort Liberté"),
        ("2111","Dérac"),
        ("2112","Acul Samedi"),
        ("2120","Ferrier"),
        ("2121","Maribahoux"),
        ("2130","Perches"),
        ("2210","Ouanaminthe"),
        ("2220","Capotille"),
        ("2230","Mont Organisé"),
        ("2310","Trou du Nord"),
        ("2320","Saint Suzanne"),
        ("2321","Dupity"),
        ("2330","Terrier Rouge"),
        ("2331","Phaëton"),
        ("2332","Paulette"),
        ("2331","Phaëton"),
        ("2340","Caracol"),
        ("2410","Vallières"),
        ("2411","Grosse Roche"),
        ("2420","Carice"),
        ("2430","Mombrun Crochu"),
        ("2431","Bois Laurence"),
    )),

    ("Département du Nord-Ouest", (
        ("3110","Port-de-Paix"),
        ("3111","La Pointe"),
        ("3120","La Tortue"),
        ("3121","Pointe des Roseaux"),
        ("3122","Mare Rouge"),
        ("3130","Bassin Bleu"),
        ("3140","Chansolme"),
        ("3210","Saint Louis du Nord"),
        ("3211","Bonneau"),
        ("3212","Guichard"),
        ("3220","Anse à Foleur"),
        ("3310","Môle Saint Nicolas"),
        ("3320","Bombardopolis"),
        ("3330","Baie de Henne"),
        ("3340","Jean-Rabel"),
    )),

    ("Département du Sud", (
        ("8110","Cayes"),
        ("8120","Torbeck"),
        ("8121","Ferme Le Blanc"),
        ("8122","Ducis"),
        ("8130","Chantal"),
        ("8140","Camp Perrin"),
        ("8150","Maniche"),
        ("8160","L’Ïle à Vaches"),
        ("8210","Port-Salut"),
        ("8220","Saint Jean du Sud"),
        ("8230","Arniquet"),
        ("8310","Aquin"),
        ("8311","Fond des Blanc"),
        ("8312","Vieux Bourg d’Aquin"),
        ("8313","La Colline"),
        ("8320","Saint Louis du Sud"),
        ("8330","Cavaillon"),
        ("8410","Côteaux"),
        ("8411","Damassin"),
        ("8412","La Côte"),
        ("8420","Port à Piment"),
        ("8430","Roche à Bateau"),
        ("8510","Chardonnières"),
        ("8511","Randel"),
        ("8520","Les Anglais"),
        ("8530","Tiburon"),
        ("8531","Cahonane"),
    )),

    ("Département du Sud-Est", (
        ("9110","Jacmel"),
        ("9111","Marbial"),
        ("9120","Marigot"),
        ("9121","Seguin"),
        ("9130","Cayes Jacmel"),
        ("9140","La Vallée de Jacmel"),
        ("9210","Bainet"),
        ("9220","Côtes de Fer"),
        ("9310","Belle-Anse"),
        ("9311","Mapou"),
        ("9320","Grand Gosier"),
        ("9321","Bodarie"),
        ("9330","Thiotte"),
        ("9340","Anse à Pitre"),
        ("9341","Banane"),
    )),

)