# Generated by Django 2.2 on 2021-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Princing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('prix', models.FloatField(default=10)),
                ('perdre', models.IntegerField(default=0)),
                ('nombres_questions', models.IntegerField(default=10)),
                ('gains', models.FloatField(default=250)),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='nombres_tours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='montant',
            field=models.FloatField(default=35),
        ),
    ]
