# Generated by Django 2.2 on 2021-09-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0002_auto_20210916_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='quizz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizz_app.quizzes'),
        ),
    ]
