# Generated by Django 2.2 on 2021-09-20 14:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0003_auto_20210920_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier_addresse', models.CharField(max_length=100)),
                ('apartement_addresse', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Département de l’Ouest', (('6110', 'Port-au-Prince'), ('6111', 'Bel-Air et Bourdon'), ('6112', 'Bas Peu de Choses'), ('6113', 'Turgeau'), ('6114', 'Bois Verna'), ('6116', 'Carrefour Feuilles'), ('6117', 'Morne de l’Hôpital'), ('6118', 'Bolosse'), ('6119', 'Martissant et Fontamara'), ('6120', 'Delmas'), ('6121', 'Varreux'), ('6122', 'Cité soleil'), ('6123', 'Maïs Gâté, Tabarre zone 1'), ('6124', 'Petite Place Cazeau, Tabarre zone 2'), ('6125', 'Croix-des-Missions'), ('6130', 'Carrefour'), ('6131', 'Bizoton'), ('6132', 'Diquini, Thor'), ('6133', 'Côte-Page, Mahotière'), ('6134', 'Arcachon, Warney'), ('6135', 'Brochette'), ('6136', 'Lamentin, Mariani, Merger'), ('6140', 'Pétion-Ville'), ('6141', 'Frères, pergnier'), ('6142', 'Pèlerin'), ('6143', 'Tête de l’Eau'), ('6144', 'Laboule'), ('6145', 'Thomassin'), ('6146', 'Fermathe'), ('6147', 'Pergnier'), ('6150', 'Kenscoff'), ('6160', 'Gressier'), ('6210', 'Léogâne'), ('6211', 'Trouin'), ('6212', 'Orangers'), ('6220', 'PetitGoâve'), ('6221', 'Vialet'), ('6230', 'Grand Goâve'), ('6310', 'Croix-des-Bouquets'), ('6311', 'Santo'), ('6312', 'Bon Repos'), ('6320', 'Thomazeau'), ('6330', 'Ganthier'), ('6331', 'Fonds Parisien et Galette Bonbon'), ('6330', 'Cornillon'), ('6340', 'Fonds Verettes'), ('6410', 'Arcahaie'), ('6411', 'Saintard'), ('6420', 'Cabaret'), ('6421', 'Casale'), ('6510', 'Anse à Galets (La Gonâve)'), ('6520', 'Pointe à Raquette (La Gonâve)'))), ('Département de l’Artibonite', (('4110', 'Gonaives'), ('4111', 'Petite Rivière de l’Artibonite'), ('4120', 'Ennery'), ('4130', 'L’Estère'), ('4210', 'Gros Morne'), ('4220', 'Terre Neuve'), ('4230', 'Anse Rouge'), ('4231', 'Sources Chaudes'), ('4310', 'Saint Marc'), ('4311', 'Montrouis'), ('4320', 'Verrettes'), ('4321', 'Désarmes'), ('4322', 'Deschapelles'), ('4323', 'Liancourt'), ('4410', 'Dessalines / Marchand'), ('4420', 'Petite Rivière del’Artibonite'), ('4421', 'Savane à Roches'), ('4430', 'Grande Saline'), ('4440', 'Desdunes'), ('4510', 'Marmelade'), ('4520', 'Saint Michel de l’Attalaye'))), ('Département de la Grande Anse', (('7110', 'Jérémie'), ('7111', 'Léon'), ('7112', 'Marfranc'), ('7120', 'Abricot'), ('7130', 'Bonbon'), ('7140', 'Moron'), ('7141', 'Sources Chaudes'), ('7150', 'Chambellan'), ('7210', 'Anse d’Hainault'), ('7220', 'Dame-Marie'), ('7221', 'lesson'), ('7230', 'LesIrois'), ('7231', 'Carcasse'), ('7310', 'Corail'), ('7320', 'Roseaux'), ('7330', 'Beaumont'), ('7340', 'Pestel'))), ('Département de Nippes', (('7410', 'Miragoâne'), ('7411', 'Saint Michel du Sud'), ('7412', 'Paillant'), ('7413', 'Fond des Nègres'), ('7420', 'Petite Rivière de Nippes'), ('7510', 'Anse-à-Veau'), ('7520', 'Baradères'), ('7521', 'Grand Boucan'), ('7530', 'Petit Trou de Nippes'), ('7540', 'L’Asile'))), ('Département du Centre', (('5110', 'Hinche'), ('5111', 'Los Palis'), ('5120', 'Maïssade'), ('5121', 'Louverture'), ('5130', 'Thomonde'), ('5140', 'Cerca Cavajal'), ('5210', 'Mirebalais'), ('5211', 'Dufailly'), ('5220', 'Saut d’Eau'), ('5230', 'Boucan Carré'), ('5231', 'Péligre'), ('5310', 'Lascahobas'), ('5320', 'Belladères'), ('5330', 'Savanette'), ('5321', 'Baptiste'), ('5410', 'Cerca-la-Source'), ('5411', 'Saltadère'), ('5412', 'La Mielle'), ('5420', 'Thomassique'))), ('Département du Nord', (('1110', 'Cap-Haïtien (la ville)'), ('1111', 'Bande du Nord (quartier du Cap)'), ('1112', 'Labadie (quartier du Cap)'), ('1113', 'Haut du Cap (quartier du Cap)'), ('1114', 'Petite Anse'), ('1120', 'Quartier Morin'), ('1130', 'Limonade'), ('1210', 'Acul du Nord'), ('1211', 'La Soufrière'), ('1220', 'Plaine du Nord'), ('1221', 'Robillard'), ('1230', 'Milot'), ('1231', 'Carrefour des Pères'), ('1310', 'Grande Rivière du Nord et'), ('1320', 'Barbon'), ('1410', 'Saint Raphaël'), ('1420', 'Dondon'), ('1430', 'Ranquitte'), ('1440', 'Pignon'), ('1450', 'La Victoire'), ('1510', 'Borgne'), ('1511', 'Petit bourg de Borgne'), ('1517', 'Côte de Fer et Fond'), ('1520', 'Port-Margot'), ('1521', 'Bayeux'), ('1522', 'Margot'), ('1610', 'Limbé'), ('1611', 'Camp Coq'), ('1620', 'Bas Limbé'), ('1710', 'Plaisance'), ('1720', 'Pilate'), ('1723', 'Ravine Trompette'))), ('Département du Nord-Est', (('2110', 'Fort Liberté'), ('2111', 'Dérac'), ('2112', 'Acul Samedi'), ('2120', 'Ferrier'), ('2121', 'Maribahoux'), ('2130', 'Perches'), ('2210', 'Ouanaminthe'), ('2220', 'Capotille'), ('2230', 'Mont Organisé'), ('2310', 'Trou du Nord'), ('2320', 'Saint Suzanne'), ('2321', 'Dupity'), ('2330', 'Terrier Rouge'), ('2331', 'Phaëton'), ('2332', 'Paulette'), ('2331', 'Phaëton'), ('2340', 'Caracol'), ('2410', 'Vallières'), ('2411', 'Grosse Roche'), ('2420', 'Carice'), ('2430', 'Mombrun Crochu'), ('2431', 'Bois Laurence'))), ('Département du Nord-Ouest', (('3110', 'Port-de-Paix'), ('3111', 'La Pointe'), ('3120', 'La Tortue'), ('3121', 'Pointe des Roseaux'), ('3122', 'Mare Rouge'), ('3130', 'Bassin Bleu'), ('3140', 'Chansolme'), ('3210', 'Saint Louis du Nord'), ('3211', 'Bonneau'), ('3212', 'Guichard'), ('3220', 'Anse à Foleur'), ('3310', 'Môle Saint Nicolas'), ('3320', 'Bombardopolis'), ('3330', 'Baie de Henne'), ('3340', 'Jean-Rabel'))), ('Département du Sud', (('8110', 'Cayes'), ('8120', 'Torbeck'), ('8121', 'Ferme Le Blanc'), ('8122', 'Ducis'), ('8130', 'Chantal'), ('8140', 'Camp Perrin'), ('8150', 'Maniche'), ('8160', 'L’Ïle à Vaches'), ('8210', 'Port-Salut'), ('8220', 'Saint Jean du Sud'), ('8230', 'Arniquet'), ('8310', 'Aquin'), ('8311', 'Fond des Blanc'), ('8312', 'Vieux Bourg d’Aquin'), ('8313', 'La Colline'), ('8320', 'Saint Louis du Sud'), ('8330', 'Cavaillon'), ('8410', 'Côteaux'), ('8411', 'Damassin'), ('8412', 'La Côte'), ('8420', 'Port à Piment'), ('8430', 'Roche à Bateau'), ('8510', 'Chardonnières'), ('8511', 'Randel'), ('8520', 'Les Anglais'), ('8530', 'Tiburon'), ('8531', 'Cahonane'))), ('Département du Sud-Est', (('9110', 'Jacmel'), ('9111', 'Marbial'), ('9120', 'Marigot'), ('9121', 'Seguin'), ('9130', 'Cayes Jacmel'), ('9140', 'La Vallée de Jacmel'), ('9210', 'Bainet'), ('9220', 'Côtes de Fer'), ('9310', 'Belle-Anse'), ('9311', 'Mapou'), ('9320', 'Grand Gosier'), ('9321', 'Bodarie'), ('9330', 'Thiotte'), ('9340', 'Anse à Pitre'), ('9341', 'Banane')))], max_length=4)),
                ('identification_type', models.CharField(choices=[('C', 'CIN'), ('P', 'Passport'), ('N', 'NIF'), ('M', 'Mot-De-Passe')], max_length=1)),
                ('identification_number', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BillingAddresses',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('prix_avec_reduction', models.FloatField(blank=True, null=True)),
                ('prix_livraison', models.FloatField()),
                ('etat', models.CharField(choices=[('N', 'Neuf'), ('U', 'Usage'), ('E', 'En bonne etat')], max_length=1)),
                ('label', models.CharField(choices=[('V', 'vente'), ('N', 'nouveau'), ('P', 'promotion')], max_length=1)),
                ('size', models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('SL', 'Longueur standard'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('SAK', 'Sak'), ('P', 'Plat'), ('KE', 'Caisse'), ('B', 'Boite'), ('C', 'Chaise'), ('U', 'Unite')], max_length=3)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title'])),
                ('quantiter_disponible', models.CharField(max_length=3)),
                ('description_court', models.CharField(max_length=100)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(upload_to='product_photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='product_photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.Category')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='market-categories/img/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('addresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='quizz_app.BillingAddress')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizz_app.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='quizz_app.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
